/*create or replace view VW_MUTASI_PENSIUN_TUNDA as
  SELECT  mp.*
  FROM TBL_T_MUTASI_PENSIUN mp
  WHERE (mp.ID_KATEGORI_MUTASI = '08' OR mp.ID_KATEGORI_MUTASI = '09' OR  mp.ID_KATEGORI_MUTASI = '10' )
    AND EXISTS (SELECT 'x' FROM TBL_T_SETUP_PARAMETER where mp.PERIODE_MUTASI = TBL_T_SETUP_PARAMETER.PERIODE AND TBL_T_SETUP_PARAMETER.IS_BUKA_PERIODE = 1)
/

create or replace view VW_PENSTUNDA_JATUHTEMPO as
  select p.*
  from tbl_m_pensiun p
         LEFT JOIN (SELECT TBL_T_MUTASI_PENSIUN.* FROM TBL_T_MUTASI_PENSIUN WHERE (ID_KATEGORI_MUTASI = '08' OR ID_KATEGORI_MUTASI = '09' OR ID_KATEGORI_MUTASI = '10')) A ON A.NIP = p.NIP
  WHERE
      (p.ID_KATEGORI_PENSIUN = 'PT' OR (p.ID_KATEGORI_PENSIUN = 'PD' AND p.ID_USIA_BAYAR =1)) AND A.NIP IS NULL
    AND exists (SELECT 'x' FROM TBL_T_SETUP_PARAMETER WHERE p.TGL_AWAL_BAYAR > TBL_T_SETUP_PARAMETER.TGL_AWAL_BAYAR AND TBL_T_SETUP_PARAMETER.IS_BUKA_PERIODE = 1)
/

create or replace view VW_PENSTUNDA_JATUHTEMPODIBAYAR as
  select p.*
  from tbl_m_pensiun p
         LEFT JOIN (SELECT TBL_T_MUTASI_PENSIUN.* FROM TBL_T_MUTASI_PENSIUN WHERE (ID_KATEGORI_MUTASI = '08' OR ID_KATEGORI_MUTASI = '09' OR ID_KATEGORI_MUTASI = '10')) A ON A.NIP = p.NIP
  WHERE
      (p.ID_KATEGORI_PENSIUN = 'PT' OR (p.ID_KATEGORI_PENSIUN = 'PD' AND p.ID_USIA_BAYAR =1)) AND A.NIP IS NULL
    AND exists (SELECT 'x' FROM TBL_T_SETUP_PARAMETER WHERE p.TGL_AWAL_BAYAR <= TBL_T_SETUP_PARAMETER.TGL_AWAL_BAYAR AND TBL_T_SETUP_PARAMETER.IS_BUKA_PERIODE = 1)
/
*/

/* PERBAIKAN STRUKTUR VIEW PENSIUN TUNDA AFTER UAT PROJECT */
/* CHANGE BY IRWAN NUGRAHA */
-- Query dari TBL_T_MUTASI_PENSIUN
create or replace view VW_PENSTUNDA_JATUHTEMPO as
  select p.*
  from tbl_m_pensiun p
         LEFT JOIN (SELECT TBL_T_MUTASI_PENSIUN.* FROM TBL_T_MUTASI_PENSIUN WHERE (ID_KATEGORI_MUTASI = '08' OR ID_KATEGORI_MUTASI = '09' OR ID_KATEGORI_MUTASI = '10')) A ON A.NIP = p.NIP
  WHERE
      (p.ID_KATEGORI_PENSIUN = 'PT') AND A.NIP IS NULL
    AND exists (SELECT 'x' FROM TBL_T_SETUP_PARAMETER WHERE TBL_T_SETUP_PARAMETER.IS_BUKA_PERIODE = 1)
